- app/javascript/components/ExamCodeBox.tsx
- package.json
- yarn.lock
marker types fixed in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44521
> update codemirror types

- app/controllers/exams_controller.rb
- app/javascript/actions/index.ts
- app/javascript/components/Body.tsx
- app/javascript/components/DisplayBody.tsx
- app/javascript/components/FileViewer.tsx
- app/javascript/components/Icon.css
- app/javascript/components/Icon.tsx
- app/javascript/components/LockdownInfo.tsx
- app/javascript/components/SnapshotInfo.tsx
- app/javascript/components/Tooltip.tsx
- app/javascript/components/TooltipButton.tsx
- app/javascript/components/navbar/AskQuestion.tsx
- app/javascript/components/navbar/ExamMessages.tsx
- app/javascript/components/navbar/ExamNavbar.css
- app/javascript/components/navbar/ExamNavbar.tsx
- app/javascript/constants.ts
- app/javascript/containers/navbar/AskQuestion.ts
- app/javascript/helpers.ts
- app/javascript/reducers/index.ts
- app/javascript/reducers/questions.ts
- app/javascript/types.ts
- app/models/exam.rb
> Improve question-asking UI

- app/models/registration.rb
- app/models/snapshot.rb
- db/migrate/20200514210728_create_snapshots.rb
- db/schema.rb
- test/fixtures/snapshots.yml
- test/fixtures/users.yml
- test/models/snapshot_test.rb
Replaces json files in `private/` with storing `jsonb` snapshots in the database.
> add snapshot model

- app/controllers/application_controller.rb
- app/views/devise/sessions/new.html.erb
store location in session instead of query param
> fix unbounded redirect

- app/javascript/components/workflows/proctor/registrations/show/DisplayBody.tsx
- app/javascript/components/workflows/student/exams/show/containers/questions/connectors.ts
> check for noAns in exam preview

- app/javascript/components/workflows/professor/exams/admin.tsx
- app/models/accommodation.rb
- app/models/exam.rb
- app/models/registration.rb
- lib/tasks/sample_data.rake
- test/factories/accommodation.rb
- test/factories/exam.rb
- test/factories/registration.rb
- test/models/accommodation_test.rb
- test/models/exam_test.rb
- test/models/registration_test.rb
> Accommodations and durations

- app/controllers/api/professor/exams_controller.rb
- app/controllers/api/professor/versions_controller.rb
- app/javascript/components/common/alerts.tsx
- app/javascript/components/common/api/professor/exams/show.ts
- app/javascript/components/common/api/professor/exams/versions/create.ts
- app/javascript/components/common/api/professor/exams/versions/delete.ts
- app/javascript/components/common/api/professor/exams/versions/show.ts
- app/javascript/components/common/linkbutton.tsx
- app/javascript/components/common/types/api.ts
- app/javascript/components/workflows/professor/exams/admin.tsx
- app/javascript/components/workflows/professor/exams/edit.tsx
- app/javascript/components/workflows/professor/exams/new/editor/components/Submit.tsx
- app/javascript/components/workflows/student/exams/show/components/Tooltip.tsx
- app/javascript/components/workflows/student/exams/show/components/TooltipButton.css
- app/javascript/components/workflows/student/exams/show/components/TooltipButton.tsx
- app/models/exam_version.rb
- app/models/registration.rb
- config/routes.rb
- config/schemas/exam-save.json
- test/controllers/api/professor/versions_controller_test.rb
- test/factories/exam.rb
- test/factories/registration.rb
- test/models/exam_test.rb
- test/models/registration_test.rb
> Create and delete versions

- app/javascript/components/common/documentTitle.tsx
- app/javascript/components/workflows/index.tsx
- app/javascript/components/workflows/professor/courses/show.tsx
- app/javascript/components/workflows/professor/exams/admin.tsx
> Add page titles

- .github/workflows/test.yml
- Gemfile
- Gemfile.lock
- app/javascript/components/workflows/student/exams/show/helpers.ts
- shell.nix
- test/application_system_test_case.rb
- test/factories/exam_version.rb
- test/system/anomalies_test.rb
- test/test_helper.rb
> nix for rails tests and capybara setup

- .rubocop.yml
- app/controllers/api/professor/accommodations_controller.rb
- app/controllers/api/professor/registrations_controller.rb
- app/controllers/api_controller.rb
- app/javascript/components/common/api/professor/accommodations/create.ts
- app/javascript/components/common/api/professor/accommodations/destroy.ts
- app/javascript/components/common/api/professor/accommodations/index.ts
- app/javascript/components/common/api/professor/accommodations/update.ts
- app/javascript/components/common/api/professor/registrations/index.ts
- app/javascript/components/workflows/professor/exams/accommodations/index.tsx
- app/javascript/components/workflows/professor/exams/admin.tsx
- app/javascript/components/workflows/professor/exams/new/DateTimePicker.tsx
- app/models/accommodation.rb
- app/models/exam.rb
- config/routes.rb
- db/migrate/20200522182009_create_schema.rb
- db/schema.rb
- lib/tasks/sample_data.rake
- test/factories/accommodation.rb
- test/factories/user.rb
> Accommodation management

- app/javascript/components/workflows/professor/exams/new/editor/components/questions/AllThatApply.tsx
- yarn.lock
> update redux form types

- app/javascript/components/workflows/proctor/registrations/show/DisplayBody.tsx
- app/javascript/components/workflows/proctor/registrations/show/DisplayQuestions.tsx
- app/javascript/components/workflows/proctor/registrations/show/Part.tsx
- app/javascript/components/workflows/proctor/registrations/show/ShowQuestion.tsx
- app/javascript/components/workflows/proctor/registrations/show/index.tsx
- app/javascript/components/workflows/professor/exams/admin.tsx
- app/javascript/components/workflows/professor/exams/new/editor/components/FilePicker.tsx
- app/javascript/components/workflows/professor/exams/new/editor/components/FileUploader.tsx
- app/javascript/components/workflows/student/exams/show/components/ExamCodeBox.tsx
- app/javascript/components/workflows/student/exams/show/components/FileViewer.tsx
- app/javascript/components/workflows/student/exams/show/components/questions/Code.tsx
> refresh codemirrors in exam editor and preview

- app/javascript/components/workflows/professor/exams/new/editor/components/FileUploader.tsx
- app/javascript/components/workflows/professor/exams/new/editor/components/Reference.tsx
- app/javascript/components/workflows/professor/exams/new/editor/index.tsx
> clear invalid file refs when uploading new zip

- app/javascript/components/workflows/student/exams/show/lockdown/helpers.ts
> Fix fullscreen check

- Gemfile
- Gemfile.lock
- app/channels/application_cable/connection.rb
- app/controllers/application_controller.rb
- app/controllers/graphql_controller.rb
- app/graphql/mutations/impersonate_user.rb
- app/graphql/mutations/stop_impersonating.rb
- app/graphql/types/base_object.rb
- app/graphql/types/mutation_type.rb
- app/graphql/types/query_type.rb
- app/graphql/types/user_type.rb
- app/javascript/components/common/navbar/index.tsx
- app/javascript/components/workflows/home/index.tsx
> Admin impersonation

- app/graphql/types/exam_type.rb
- app/graphql/types/user_type.rb
- app/javascript/components/workflows/home/index.tsx
- app/javascript/components/workflows/proctor/exams/index.tsx
Show exams ready for proctoring for each of the current user's proctor registrations.
> homepage for proctors

- .gitignore
- .rubocop.yml
- app/graphql/types/course_type.rb
- app/graphql/types/staff_registration_type.rb
- app/graphql/types/user_type.rb
- app/javascript/components/common/loading.tsx
- app/javascript/components/workflows/proctor/registrations/show/DisplayBody.tsx
- app/javascript/components/workflows/proctor/registrations/show/Part.tsx
- app/javascript/components/workflows/proctor/registrations/show/ShowQuestion.tsx
- app/javascript/components/workflows/proctor/registrations/show/questions/DisplayCode.tsx
- app/javascript/components/workflows/proctor/registrations/show/questions/DisplayMatching.tsx
- app/javascript/components/workflows/proctor/registrations/show/questions/DisplayMultipleChoice.tsx
- app/javascript/components/workflows/professor/exams/new/editor/components/CustomEditor.tsx
- app/javascript/components/workflows/student/exams/show/components/HTML.tsx
- app/javascript/components/workflows/student/exams/show/components/Part.tsx
- app/javascript/components/workflows/student/exams/show/components/ShowQuestion.tsx
- app/javascript/components/workflows/student/exams/show/components/questions/AllThatApply.tsx
- app/javascript/components/workflows/student/exams/show/components/questions/CodeTag.tsx
- app/javascript/components/workflows/student/exams/show/components/questions/MultipleChoice.tsx
- app/javascript/components/workflows/student/exams/show/components/questions/Text.tsx
- app/javascript/components/workflows/student/exams/show/components/questions/YesNo.tsx
- app/models/staff_registration.rb
- app/models/user.rb
Cherry-picked updates from the grading branch that are not directly related to adding grading.
Reduces the amount of work required to rebase the grading branch
> Updates from grading

- app/controllers/api/student/exams_controller.rb
- app/graphql/types/exam_version_type.rb
- app/javascript/components/common/navbar/index.tsx
- app/javascript/components/workflows/index.tsx
- app/javascript/components/workflows/proctor/exams/index.tsx
- app/javascript/components/workflows/proctor/registrations/show/DisplayBody.tsx
- app/javascript/components/workflows/student/exams/show/actions/index.ts
- app/javascript/components/workflows/student/exams/show/components/SubmitButton.tsx
- app/javascript/components/workflows/student/exams/show/components/Tooltip.tsx
- app/javascript/components/workflows/student/exams/show/components/navbar/ExamMessages.tsx
- app/javascript/components/workflows/student/exams/show/lockdown/anomaly.ts
- app/javascript/components/workflows/student/exams/show/lockdown/helpers.ts
- app/javascript/components/workflows/student/exams/show/lockdown/lock.ts
- app/models/exam.rb
- app/models/upload.rb
- app/models/user.rb
- test/fixtures/files/cs3500final-v1/exam.yaml
- test/fixtures/files/cs3500final-v2/exam.yaml
- test/integration/finalization_test.rb
> Clear todos

- app/javascript/components/workflows/index.tsx
- app/javascript/components/workflows/student/exams/show/actions/index.ts
- app/javascript/components/workflows/student/exams/show/components/ExamShowContents.tsx
- app/javascript/components/workflows/student/exams/show/components/ShowQuestion.tsx
- app/javascript/components/workflows/student/exams/show/containers/ExamShowContents.ts
- app/javascript/components/workflows/student/exams/show/containers/SubmitButton.ts
- app/javascript/components/workflows/student/exams/show/lockdown/anomaly.ts
- app/javascript/components/workflows/student/exams/show/lockdown/listeners.ts
> firefox: fix infinite loop on submit

- app/graphql/mutations/destroy_anomaly.rb
- app/graphql/types/exam_type.rb
- app/models/anomaly.rb
- app/models/registration.rb
- db/migrate/20200522182009_create_schema.rb
- db/schema.rb
> save removed anomalies

- app/javascript/components/workflows/professor/exams/new/editor/components/questions/YesNo.tsx
If an answer has not been chosen yet, do not highlight the "No" option
> fix yes-no

- app/graphql/mutations/ask_question.rb
- app/graphql/subscriptions/question_was_asked.rb
- app/helpers/uploads_helper.rb
- app/javascript/components/workflows/index.tsx
- app/javascript/components/workflows/proctor/exams/index.tsx
Stuff I found while trying the tutorial exam
> More fixes

- app/javascript/components/workflows/home/index.tsx
> Add key prop to Terms

- app/helpers/application_helper.rb
- app/models/part.rb
- app/models/question.rb
> Add HTML wrapper to question and part names and descriptions

- app/graphql/types/user_type.rb
- app/javascript/components/workflows/home/index.tsx
- app/javascript/components/workflows/index.scss
- app/javascript/components/workflows/professor/courses/show.tsx
- app/models/user.rb
> show usernames and photos in impersonation dropdowns

- app/packs/components/workflows/index.scss
- app/packs/components/workflows/student/exams/show/components/navbar/TimeRemaining.tsx
- app/packs/components/workflows/student/exams/show/components/navbar/index.tsx
> Change dolphin glow in navbar to match warning color from timer

- app/packs/components/workflows/student/exams/show/components/VerticalScrollShadow.scss
- app/packs/components/workflows/student/exams/show/components/VerticalScrollShadow.tsx
- app/packs/components/workflows/student/exams/show/components/navbar/ExamMessages.tsx
- app/packs/components/workflows/student/exams/show/components/navbar/index.tsx
The navbar accordion area is now scrollable, and shows shadows at the top and bottom to indicate that scrolling is available in those directions: 
The scroll-indicators have only been tested in Firefox so far, but they should work in any modern browser.
> Fixes #396. 
